version: "3.7"

services:
  hangman:
    image: python:3.9-buster
    command: sudo git clone https://github.com/hverton1a/hangman.git
    command: sh -C "pip3 install -r ./backend/requirements.txt "
    command: sh -C "python -m main"
    ports:
      - 5000:5000
    network:
      - db-net
    working_dir: /hangman
    volumes:
      - ./:/hangman
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos

  mysql:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - db-net
    alias:
      - mysqldb
    environment: 
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos

volumes:
  db-data:

networks:
  db-net:
    driver: custom-driver-1