"""test on fake tables and relationsships

Revision ID: 5af11439c9fa
Revises: ac87d5d5a25f
Create Date: 2022-01-14 20:32:39.747927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5af11439c9fa'
down_revision = 'ac87d5d5a25f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words_fake',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word', sa.String(length=50), nullable=True),
    sa.Column('msg', sa.String(length=100), nullable=True),
    sa.Column('letters', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_fake_id'), 'words_fake', ['id'], unique=False)
    op.create_index(op.f('ix_words_fake_word'), 'words_fake', ['word'], unique=False)
    op.create_table('fake_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.Column('games', sa.Integer(), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['words_fake.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fake_stats_id'), 'fake_stats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fake_stats_id'), table_name='fake_stats')
    op.drop_table('fake_stats')
    op.drop_index(op.f('ix_words_fake_word'), table_name='words_fake')
    op.drop_index(op.f('ix_words_fake_id'), table_name='words_fake')
    op.drop_table('words_fake')
    # ### end Alembic commands ###
