"""Added Superuser and token tables

Revision ID: 904dcb9f4205
Revises: e0df6b15735d
Create Date: 2022-03-08 20:11:19.774028

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '904dcb9f4205'
down_revision = 'e0df6b15735d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('superuser',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('superuser', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_superuser_id'), 'superuser', ['id'], unique=False)
    op.create_index(op.f('ix_superuser_superuser'), 'superuser', ['superuser'], unique=True)
    op.create_table('token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=250), nullable=True),
    sa.Column('superuser_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['superuser_id'], ['superuser.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_id'), 'token', ['id'], unique=False)
    op.create_index(op.f('ix_token_token'), 'token', ['token'], unique=True)
    op.drop_index('ix_words_fake_id', table_name='words_fake')
    op.drop_index('ix_words_fake_word', table_name='words_fake')
    op.drop_table('words_fake')
    op.drop_index('ix_fake_stats_id', table_name='fake_stats')
    op.drop_table('fake_stats')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fake_stats',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('word_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('games', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('hits', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['words_fake.id'], name='fake_stats_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_fake_stats_id', 'fake_stats', ['id'], unique=False)
    op.create_table('words_fake',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('word', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('msg', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('letters', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_words_fake_word', 'words_fake', ['word'], unique=False)
    op.create_index('ix_words_fake_id', 'words_fake', ['id'], unique=False)
    op.drop_index(op.f('ix_token_token'), table_name='token')
    op.drop_index(op.f('ix_token_id'), table_name='token')
    op.drop_table('token')
    op.drop_index(op.f('ix_superuser_superuser'), table_name='superuser')
    op.drop_index(op.f('ix_superuser_id'), table_name='superuser')
    op.drop_table('superuser')
    # ### end Alembic commands ###
