"""add project tables from word models word, statistics, hints, language

Revision ID: e0df6b15735d
Revises: 5af11439c9fa
Create Date: 2022-01-21 13:57:57.468418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0df6b15735d'
down_revision = '5af11439c9fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language')
    )
    op.create_table('word',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word', sa.String(length=50), nullable=True),
    sa.Column('playword', sa.String(length=50), nullable=True),
    sa.Column('letters', sa.Integer(), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_id'), 'word', ['id'], unique=False)
    op.create_index(op.f('ix_word_playword'), 'word', ['playword'], unique=True)
    op.create_index(op.f('ix_word_word'), 'word', ['word'], unique=True)
    op.create_table('hints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hint', sa.String(length=200), nullable=True),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statistics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('games', sa.Integer(), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statistics')
    op.drop_table('hints')
    op.drop_index(op.f('ix_word_word'), table_name='word')
    op.drop_index(op.f('ix_word_playword'), table_name='word')
    op.drop_index(op.f('ix_word_id'), table_name='word')
    op.drop_table('word')
    op.drop_table('language')
    # ### end Alembic commands ###
